"use client"

import { Suspense } from 'react'
import { motion } from 'framer-motion'
import { 
  Code, 
  FileText, 
  Star, 
  GitBranch, 
  Eye, 
  Download,
  Zap,
  Sparkles,
  ArrowRight,
  Copy,
  Heart
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import LayoutWrapper from '@/components/layout-wrapper'
import PageHeader from '@/components/layout/page-header'
import ContentSection from '@/components/layout/content-section'

function ExamplesContent() {
  const examples = [
    {
      title: "React TypeScript App",
      description: "Modern React application with TypeScript, featuring comprehensive documentation, installation guides, and usage examples.",
      language: "TypeScript",
      stars: "2.4k",
      forks: "312",
      color: "from-blue-400 to-blue-600",
      repo: "react-typescript-starter",
      author: "Sarah Chen",
      company: "TechCorp",
      generatedIn: "28s",
      features: ["Component Documentation", "API Reference", "Testing Guide", "Deployment Instructions"],
      preview: `# React TypeScript Starter 🚀

A modern, fully-typed React application starter template with best practices and comprehensive tooling.

## ✨ Features

- ⚡ **Vite** for lightning-fast development
- 🔷 **TypeScript** for type safety
- ⚛️ **React 18** with latest features
- 🎨 **Tailwind CSS** for styling
- 📦 **Component Library** ready

## 🚀 Quick Start

\`\`\`bash
npm install
npm run dev
\`\`\`

## 📖 Documentation

Visit our [documentation](./docs) for detailed guides and API references.`
    }
  ];

  return (
    <LayoutWrapper>
      <PageHeader
        title="Showcase Examples"
        description="Explore real-world READMEs generated by AutoDoc AI for various project types and see the quality and detail our AI can achieve."
        badge="Real Project Examples"
        icon={Sparkles}
      />

      <ContentSection background="none" padding="none">
        <div className="grid gap-8">
          {examples.map((example, index) => (
            <motion.div
              key={example.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1, duration: 0.5 }}
              className="glass-card p-8 group"
            >
              <div className="flex flex-col lg:flex-row gap-8">
                <div className="lg:w-1/3">
                  <div className="flex items-center gap-3 mb-4">
                    <div className={`w-12 h-12 bg-gradient-to-r ${example.color} rounded-xl flex items-center justify-center`}>
                      <Code className="w-6 h-6 text-white" />
                    </div>
                    <div>
                      <h3 className="text-xl font-bold text-white">{example.title}</h3>
                      <p className="text-sm text-gray-400">{example.language}</p>
                    </div>
                  </div>
                  
                  <p className="text-gray-300 mb-6 leading-relaxed">
                    {example.description}
                  </p>
                  
                  <div className="space-y-4">
                    <div className="flex items-center gap-4 text-sm">
                      <div className="flex items-center gap-1">
                        <Star className="w-4 h-4 text-yellow-400" />
                        <span className="text-white font-semibold">{example.stars}</span>
                      </div>
                      <div className="flex items-center gap-1">
                        <GitBranch className="w-4 h-4 text-blue-400" />
                        <span className="text-white font-semibold">{example.forks}</span>
                      </div>
                      <div className="text-green-400 font-semibold">
                        Generated in {example.generatedIn}
                      </div>
                    </div>
                    
                    <div className="flex flex-wrap gap-2">
                      {example.features.map((feature) => (
                        <span
                          key={feature}
                          className="px-3 py-1 bg-green-400/10 text-green-400 rounded-full text-xs font-medium border border-green-400/20"
                        >
                          {feature}
                        </span>
                      ))}
                    </div>
                    
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        className="glass-button border-none text-green-400 hover:bg-green-400/20"
                      >
                        <Eye className="w-4 h-4 mr-2" />
                        Preview
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="glass-button border-none text-blue-400 hover:bg-blue-400/20"
                      >
                        <Copy className="w-4 h-4 mr-2" />
                        Copy
                      </Button>
                    </div>
                  </div>
                </div>
                
                <div className="lg:w-2/3">
                  <div className="glass-card bg-gray-900/50 p-6 rounded-xl border border-green-400/20">
                    <div className="flex items-center justify-between mb-4">
                      <div className="flex items-center gap-2">
                        <FileText className="w-4 h-4 text-green-400" />
                        <span className="text-sm font-medium text-green-400">README.md</span>
                      </div>
                      <div className="flex gap-2">
                        <Button size="sm" variant="ghost" className="h-6 px-2 text-xs">
                          <Download className="w-3 h-3 mr-1" />
                          Download
                        </Button>
                      </div>
                    </div>
                    
                    <div className="bg-black/50 rounded-lg p-4 font-mono text-sm overflow-x-auto">
                      <pre className="text-gray-300 whitespace-pre-wrap">
                        {example.preview}
                      </pre>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </ContentSection>

      <ContentSection background="gradient" className="text-center">
        <div className="relative">
          <Heart className="w-16 h-16 text-green-400 mx-auto mb-6" />
          <h2 className="text-4xl font-bold text-white mb-4">
            Ready to Create Your Own?
          </h2>
          <p className="text-xl text-gray-400 mb-8 max-w-2xl mx-auto">
            Join thousands of developers who have transformed their documentation workflow with AutoDoc AI.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button
              onClick={() => window.location.href = '/'}
              className="bg-green-600 hover:bg-green-700 text-white px-8 py-4 text-lg font-semibold rounded-xl shadow-lg shadow-green-500/25 transition-all duration-300 hover:shadow-green-500/40 hover:scale-105"
            >
              <Zap className="w-5 h-5 mr-2" />
              Start Creating
              <ArrowRight className="w-5 h-5 ml-2" />
            </Button>
            
            <Button
              onClick={() => window.location.href = '/features'}
              variant="outline"
              className="border-green-400/50 text-green-400 hover:bg-green-400/10 px-8 py-4 text-lg font-semibold rounded-xl transition-all duration-300 hover:border-green-400"
            >
              <Sparkles className="w-5 h-5 mr-2" />
              View Features
            </Button>
          </div>
        </div>
      </ContentSection>
    </LayoutWrapper>
  );
}

export default function ExamplesPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <ExamplesContent />
    </Suspense>
  );
}