import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'ReadmeArchitect - AI-Powered README Generator | Create Professional GitHub Documentation',
  description: 'Generate professional README files for your GitHub repositories using advanced AI. Create beautiful, comprehensive documentation in under 30 seconds. Trusted by 15,000+ developers worldwide with 99.2% accuracy.',
  keywords: [
    'README generator',
    'AI README generator', 
    'free README generator',
    'GitHub README generator',
    'automatic README creator',
    'GitHub documentation',
    'AI documentation generator',
    'README maker',
    'repository documentation',
    'GitHub tools',
    'markdown generator',
    'documentation automation',
    'code documentation',
    'project documentation',
    'developer tools',
    'GitHub integration',
    'AI writing assistant',
    'technical documentation',
    'software documentation',
    'open source tools',
    'ReadmeArchitect',
    'professional documentation',
    'AI-powered tools',
    'developer productivity',
    'documentation templates'
  ],
  authors: [{ name: 'ReadmeArchitect' }],
  creator: 'ReadmeArchitect',
  publisher: 'ReadmeArchitect',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon.ico', type: 'image/x-icon' },
    ],
    shortcut: '/favicon.ico',
  },
  manifest: '/site.webmanifest',
  openGraph: {
    title: 'ReadmeArchitect - AI-Powered README Generator | Create Professional GitHub Documentation',
    description: 'Generate professional README files for your GitHub repositories using advanced AI. Trusted by 15,000+ developers worldwide with 99.2% accuracy.',
    url: 'https://readmearchitect.vercel.app',
    siteName: 'ReadmeArchitect',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'ReadmeArchitect - AI-Powered README Generator Interface',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'ReadmeArchitect - AI-Powered README Generator',
    description: 'Generate professional README files for your GitHub repositories using advanced AI. Trusted by 15,000+ developers worldwide.',
    images: ['/og-image.png'],
    creator: '@readmearchitect',
    site: '@readmearchitect',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};